# Travis CI build for pygount.
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --requirement dev-requirements.txt

script:
  # Validate coding guidelines.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pre-commit run --all-files; fi
  # Run the test suite.
  - python setup.py develop
  - pytest --verbose
  # Build and install the package.
  - python setup.py bdist_wheel
  - python setup.py install

after_success:
  - coveralls
